version: '2'
services:
  web:
    build: ./web-client/.
    ports: 
     - "8080:8080"
    depends_on:
     - inventory
  discovery:
    build: ./discovery-server/.
    ports:
     - "1111:1111"
  inventory:
    build: ./inventory/.
    ports:
     - "2222:2222"
    depends_on:
     - mongo
     - discovery
  sales:
    build: ./sales/.
    ports:
     - "3333:3333"
    depends_on:
     - sales-db
     - discovery
  mongo:
    image: mongo
  sales-db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: admin
        POSTGRES_USER: admin
        POSTGRES_DB: sales
  queue:
    image: rabbitmq:3.6.9-management-alpine
    ports:
     - "15672:15672"
    environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: admin
    