### Spring properties
# Service registers under this name
spring:
  application:
    name: inventory-service
  cloud:
    stream:
      bindings:
        input:
          destination: ex.stream.out
          group: product
          binder: rabbit1
        output:
          destination: ex.stream.out2
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: queue
                port: 5672
                username: admin
                password: admin

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://discovery:1111/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 2222